default:
  image: node:latest

cache:
  paths:
    - website/node_modules/
    - monitor/node_modules/

pages:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    paths:
      - public
      - website/node_modules/
      - monitor/node_modules/
  before_script:
    - "which git || ( apt-get update -y && apt-get install git -y )"
    - git config user.name "uptime"
    - git config user.email "<>"
    - git config push.default "current"
    - cd website; npm ci --only=prod; cd ..
    - cd monitor; npm ci --only=prod; cd ..
  script:
    - git remote rm origin || true
    - git remote add origin "https://${GITLAB_USER_NAME}:${CI_ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}"
    - git checkout $CI_COMMIT_BRANCH || git checkout -b $CI_COMMIT_BRANCH
    - git fetch
    - git branch --set-upstream-to=origin/$CI_COMMIT_BRANCH $CI_COMMIT_BRANCH
    - git pull
    - cd monitor; npm run ci; cd ..
    - cd website; npm run ci:withdata; cd ..
