host: "http://localhost:3000/data/{{site}}.csv"
owner: myusername
repo: myreponame
branch: main

sites:
  - name: Google
    url: https://www.google.com

githost_url: "https://github.com/lil5/uptime-anywhere"
