on:
  workflow_dispatch:
  schedule:
    - cron: "2 * * * *"

jobs:
  monitor:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          git config user.name "uptime"
          git config user.email "<>"
          git config push.default "current"
          ./run
