on:
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          git config user.name "uptime"
          git config user.email "<>"
          git config push.default "current"
      - uses: crazy-max/ghaction-github-pages@v2
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: public
