on:
  workflow_dispatch:
  pull_request:
  release:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install NodeJS 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          cd monitor; npm ci; cd ..
          cd website; npm ci; cd ..
      - name: Run Test
        run: |
          cd monitor; npm run test; cd ..
          cd website; npm run test; cd ..
