on:
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup git config
        shell: bash
        run: |
          git config user.name "uptime"
          git config user.email "<>"
          git config push.default "current"
      - name: Install NodeJS 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: cd website; npm ci --only=prod; cd ..
      - name: Run Build
        run: cd website; npm run ci; cd ..
      - name: Push to github pages
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: public
